webtalk_init -webtalk_dir E:\\projects\\xilinix\\master_repo\\LAB_AEP\\Integrated_redo_\\hdl\\Projects\\fmc_imageon_gs\\ZEDBOARD\\fmc_imageon_gs.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun 7 20:26:02 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2s12r9ju0mifc36007q1ta7c66" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1465323795740" -context "sdk\\\\bsp/1465323795740"
webtalk_add_data -client sdk -key hwid -value "1465323206150" -context "sdk\\\\bsp/1465323795740"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1465323795740"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1465323795740"
webtalk_transmit -clientid 1005688322 -regid "" -xml E:\\projects\\xilinix\\master_repo\\LAB_AEP\\Integrated_redo_\\hdl\\Projects\\fmc_imageon_gs\\ZEDBOARD\\fmc_imageon_gs.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\projects\\xilinix\\master_repo\\LAB_AEP\\Integrated_redo_\\hdl\\Projects\\fmc_imageon_gs\\ZEDBOARD\\fmc_imageon_gs.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\projects\\xilinix\\master_repo\\LAB_AEP\\Integrated_redo_\\hdl\\Projects\\fmc_imageon_gs\\ZEDBOARD\\fmc_imageon_gs.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
